
import React, { useState, useMemo, useEffect } from 'react';
import { GoogleGenAI, Type } from "@google/genai";
import { TrashIcon, ArrowUpRightIcon, CloseIcon, DocumentTextIcon, ExclamationTriangleIcon, MicrophoneIcon, SparklesIcon, CheckCircleIcon, LogoIcon } from './Icons';
import type { Risk, Permission, RiskTreatmentOption, ControlEffectiveness, PolicyDocument } from '../types';
import { likelihoodOptions, impactOptions, prebuiltRiskRegister } from '../data/riskAssessmentData';
import { KhalidAssistant } from './KhalidAssistant';

const getRiskScoreInfo = (score: number): { text: string, color: string } => {
  if (score <= 5) return { text: 'Low', color: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200' };
  if (score <= 10) return { text: 'Medium', color: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200' };
  if (score <= 15) return { text: 'High', color: 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200' };
  if (score <= 20) return { text: 'Very High', color: 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200' };
  return { text: 'Critical', color: 'bg-red-200 text-red-900 dark:bg-red-900/50 dark:text-red-100 font-bold' };
};

interface RiskAssessmentPageProps {
    risks: Risk[];
    setRisks: (updater: React.SetStateAction<Risk[]>) => void;
    status: 'idle' | 'in-progress';
    onInitiate: () => void;
    onComplete: () => void;
    permissions: Set<Permission>;
    onGenerateReport?: (filteredRisks: Risk[]) => void;
    onAddDocument?: (doc: PolicyDocument) => void;
}

export const RiskAssessmentPage: React.FC<RiskAssessmentPageProps> = ({ risks, setRisks, status, onInitiate, onComplete, permissions, onGenerateReport, onAddDocument }) => {
    const [editingRisk, setEditingRisk] = useState<Risk | null>(null);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [showInitiationOptions, setShowInitiationOptions] = useState(false);
    
    // Khalid (Rashid) AI State
    const [isKhalidActive, setIsKhalidActive] = useState(false);
    const [activeField, setActiveField] = useState<keyof Risk | null>(null);
    const [aiRiskDraft, setAiRiskDraft] = useState<Partial<Risk>>({});

    const isEditable = status === 'in-progress' && permissions.has('riskAssessment:update');

    const handleSaveRisk = (updatedRisk: Risk) => {
        setRisks(prev => {
            const exists = prev.find(r => r.id === updatedRisk.id);
            if (exists) return prev.map(r => r.id === updatedRisk.id ? updatedRisk : r);
            return [...prev, updatedRisk];
        });
        setIsModalOpen(false);
        setEditingRisk(null);
    };

    const handleLoadPrebuilt = () => {
        setRisks(prebuiltRiskRegister);
        onInitiate();
        setShowInitiationOptions(false);
    };

    const handleAddNewRisk = () => {
        setRisks([]);
        onInitiate();
        setShowInitiationOptions(false);
        setEditingRisk(null);
        setIsModalOpen(true);
    };

    const handleStartAiAssessment = () => {
        onInitiate();
        setAiRiskDraft({});
        setIsModalOpen(true);
        setIsKhalidActive(true);
        setShowInitiationOptions(false);
    };

    const handleGenerateOfficialReport = () => {
        if (!onAddDocument) return;
        
        const summary = `Risk Register contains ${risks.length} entries. Average Residual Risk: ${
            (risks.reduce((acc, r) => acc + (r.residualScore || 0), 0) / risks.length).toFixed(1)
        }. Critical Risks: ${risks.filter(r => r.inherentScore >= 20).length}.`;

        const reportDoc: PolicyDocument = {
            id: `REPORT-RISK-${Date.now()}`,
            controlId: 'REPORT-ISO-31000',
            domainName: 'Risk Management',
            subdomainTitle: 'Enterprise Risk Register',
            controlDescription: 'Comprehensive risk assessment results generated by Rashid AI.',
            status: 'Pending CISO Approval',
            content: {
                policy: `## Executive Summary\n${summary}\n\n## Detailed Register\n| Title | Inherent | Residual | Status |\n|---|---|---|---|\n` + 
                        risks.map(r => `| ${r.title} | ${r.inherentScore} | ${r.residualScore} | ${r.progress}% |`).join('\n'),
                procedure: "Assessed via Metaworks specialized Risk Lead Rashid AI.",
                guideline: "Treat according to ISO 31000 standards."
            },
            approvalHistory: [],
            createdAt: Date.now(),
            updatedAt: Date.now(),
            generatedBy: 'AI Agent',
            versionHistory: []
        };
        
        onAddDocument(reportDoc);
        alert("Strategic Risk Report generated and archived in Document Management.");
    };

    return (
        <div className="space-y-8 animate-fade-in">
            <div className="flex flex-wrap justify-between items-start gap-4">
                <div>
                    <h1 className="text-4xl font-bold text-gray-800 dark:text-gray-100 tracking-tight flex items-center gap-3">
                        Risk Assessment Lead: Rashid AI
                    </h1>
                    <p className="mt-2 text-lg text-gray-500 dark:text-gray-400">Enterprise Lifecycle Risk Management aligned with ISO 31000.</p>
                </div>
                <div className="flex-shrink-0 flex items-center gap-2 flex-wrap">
                    {risks.length > 0 && (
                        <button onClick={handleGenerateOfficialReport} className="inline-flex items-center px-4 py-2 border border-gray-300 dark:border-gray-600 text-sm font-medium rounded-xl text-gray-700 dark:text-gray-200 bg-white dark:bg-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600 shadow-sm">
                            <DocumentTextIcon className="w-4 h-4 mr-2" />
                            Archive Official Report
                        </button>
                    )}
                    {status === 'idle' ? (
                        <button onClick={() => setShowInitiationOptions(true)} className="px-6 py-2.5 bg-teal-600 text-white rounded-xl font-bold text-sm uppercase tracking-widest shadow-lg shadow-teal-500/20 hover:bg-teal-700">
                            Initiate Assessment
                        </button>
                    ) : (
                        <div className="flex gap-2">
                             <button onClick={() => { setEditingRisk(null); setIsModalOpen(true); }} className="px-4 py-2 bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-200 rounded-xl font-bold text-xs uppercase">
                                + Manual Risk
                            </button>
                            <button onClick={() => setIsKhalidActive(true)} className="px-4 py-2 bg-purple-600 text-white rounded-xl font-bold text-xs uppercase flex items-center gap-2">
                                <MicrophoneIcon className="w-4 h-4" />
                                Resume Rashid AI
                            </button>
                        </div>
                    )}
                </div>
            </div>

            {/* INITIATION OPTIONS MODAL */}
            {showInitiationOptions && (
                <div className="fixed inset-0 bg-black/60 z-[160] flex items-center justify-center p-4 backdrop-blur-sm">
                    <div className="bg-white dark:bg-gray-800 rounded-[2.5rem] shadow-2xl w-full max-w-2xl overflow-hidden p-10 border border-gray-100 dark:border-gray-700 animate-slide-up">
                        <div className="flex justify-between items-start mb-8">
                             <div>
                                <h2 className="text-2xl font-black text-gray-900 dark:text-white uppercase tracking-tighter italic">Initiation Protocol</h2>
                                <p className="text-sm text-gray-500 mt-1">Select the starting point for your organizational risk cycle.</p>
                             </div>
                             <button onClick={() => setShowInitiationOptions(false)} className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-full transition-colors"><CloseIcon className="w-6 h-6"/></button>
                        </div>
                        
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                            <button 
                                onClick={handleLoadPrebuilt}
                                className="flex flex-col items-center justify-center gap-4 p-8 bg-gray-50 dark:bg-gray-900 rounded-3xl border border-gray-100 dark:border-gray-800 hover:border-teal-500 transition-all group"
                            >
                                <div className="w-16 h-16 bg-teal-50 dark:bg-teal-900/30 text-teal-600 flex items-center justify-center rounded-2xl group-hover:scale-110 transition-transform">
                                    <LogoIcon className="w-10 h-10" />
                                </div>
                                <div className="text-center">
                                    <h3 className="font-bold text-gray-900 dark:text-white uppercase tracking-widest text-xs">Prebuilt Register</h3>
                                    <p className="text-[10px] text-gray-400 mt-1">Load common industry risks for fast benchmarking.</p>
                                </div>
                            </button>

                            <button 
                                onClick={handleStartAiAssessment}
                                className="flex flex-col items-center justify-center gap-4 p-8 bg-teal-600 rounded-3xl border border-transparent shadow-xl shadow-teal-500/20 hover:bg-teal-700 transition-all group"
                            >
                                <div className="w-16 h-16 bg-white/10 text-white flex items-center justify-center rounded-2xl group-hover:scale-110 transition-transform">
                                    <MicrophoneIcon className="w-10 h-10" />
                                </div>
                                <div className="text-center">
                                    <h3 className="font-bold text-white uppercase tracking-widest text-xs">Rashid AI Guide</h3>
                                    <p className="text-[10px] text-teal-100 mt-1">Voice-driven autonomous identification & analysis.</p>
                                </div>
                            </button>
                        </div>

                        <div className="mt-8 pt-8 border-t border-gray-100 dark:border-gray-700">
                             <button onClick={handleAddNewRisk} className="w-full py-3 text-sm font-bold text-gray-500 hover:text-gray-900 dark:hover:text-white transition-colors uppercase tracking-widest">
                                &rarr; Start from scratch with manual input
                             </button>
                        </div>
                    </div>
                </div>
            )}

            {/* RISK LIST Table */}
            <div className="bg-white dark:bg-gray-800 rounded-[2rem] shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden">
                <table className="min-w-full divide-y divide-gray-100 dark:divide-gray-800">
                    <thead className="bg-gray-50 dark:bg-gray-900/50">
                        <tr>
                            <th className="px-8 py-5 text-left text-[10px] font-black text-gray-400 uppercase tracking-widest">Category</th>
                            <th className="px-8 py-5 text-left text-[10px] font-black text-gray-400 uppercase tracking-widest">Risk Description</th>
                            <th className="px-8 py-5 text-left text-[10px] font-black text-gray-400 uppercase tracking-widest">Score (Residual)</th>
                            <th className="px-8 py-5 text-left text-[10px] font-black text-gray-400 uppercase tracking-widest">Lifecycle</th>
                            <th className="px-8 py-5 text-right text-[10px] font-black text-gray-400 uppercase tracking-widest">Action</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-50 dark:divide-gray-800">
                        {risks.map(risk => (
                            <tr key={risk.id} className="hover:bg-gray-50 dark:hover:bg-gray-900/50 transition-colors">
                                <td className="px-8 py-6">
                                    <span className="px-3 py-1 bg-gray-100 dark:bg-gray-700 rounded-full text-[9px] font-black text-gray-500 dark:text-gray-300 uppercase tracking-widest">
                                        {risk.category}
                                    </span>
                                </td>
                                <td className="px-8 py-6">
                                    <p className="text-sm font-bold text-gray-900 dark:text-white">{risk.title}</p>
                                    <p className="text-[11px] text-gray-400 line-clamp-1 mt-1 font-medium">{risk.description}</p>
                                </td>
                                <td className="px-8 py-6">
                                    <div className="flex items-center gap-3">
                                        <span className={`w-8 h-8 rounded-lg flex items-center justify-center text-xs font-black italic ${getRiskScoreInfo(risk.residualScore).color}`}>
                                            {risk.residualScore}
                                        </span>
                                        <span className="text-[10px] font-bold text-gray-500 uppercase tracking-tighter">
                                            {getRiskScoreInfo(risk.residualScore).text}
                                        </span>
                                    </div>
                                </td>
                                <td className="px-8 py-6">
                                    <div className="w-32">
                                        <div className="flex justify-between items-center mb-1 text-[9px] font-black uppercase text-gray-400">
                                            <span>Progress</span>
                                            <span>{risk.progress}%</span>
                                        </div>
                                        <div className="w-full bg-gray-100 dark:bg-gray-700 h-1.5 rounded-full overflow-hidden">
                                            <div className="bg-teal-500 h-full transition-all duration-1000" style={{ width: `${risk.progress}%` }}></div>
                                        </div>
                                    </div>
                                </td>
                                <td className="px-8 py-6 text-right">
                                    <button onClick={() => { setEditingRisk(risk); setIsModalOpen(true); }} className="p-2 text-teal-600 hover:bg-teal-50 dark:hover:bg-teal-900/30 rounded-xl transition-all">
                                        <ArrowUpRightIcon className="w-5 h-5" />
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                {risks.length === 0 && (
                    <div className="text-center py-20">
                        <ExclamationTriangleIcon className="w-16 h-16 mx-auto text-gray-200 mb-4" />
                        <p className="text-sm font-black text-gray-400 uppercase tracking-widest">No Assessment Data Found</p>
                        <p className="text-xs text-gray-500 mt-1">Initiate a session or upload a register to begin.</p>
                    </div>
                )}
            </div>

            {isModalOpen && (
                <div className="fixed inset-0 bg-black/60 z-[170] flex items-center justify-center p-4 backdrop-blur-md">
                     <div className="bg-white dark:bg-gray-800 rounded-[3rem] shadow-2xl w-full max-w-5xl h-[90vh] flex flex-col overflow-hidden border border-gray-100 dark:border-gray-700">
                        <header className="p-8 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center">
                            <h2 className="text-xl font-black uppercase italic tracking-tighter text-gray-900 dark:text-white">
                                Risk Analysis Profile
                            </h2>
                            <button onClick={() => setIsModalOpen(false)} className="p-3 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-2xl"><CloseIcon className="w-6 h-6"/></button>
                        </header>
                        <main className="flex-1 p-8 overflow-y-auto">
                            <p className="text-gray-500 mb-8 italic">Manual override interface for detailed risk parameter tuning.</p>
                            {/* Form would go here, simplified for space */}
                            <div className="grid grid-cols-2 gap-8">
                                <div className="space-y-6">
                                    <label className="block text-[10px] font-black uppercase text-gray-400 tracking-widest">Identification</label>
                                    <input type="text" placeholder="Title" className="w-full p-4 bg-gray-50 dark:bg-gray-900 rounded-2xl border-none font-bold" />
                                    <textarea placeholder="Description" className="w-full p-4 bg-gray-50 dark:bg-gray-900 rounded-2xl border-none" rows={4} />
                                </div>
                                <div className="space-y-6">
                                    <label className="block text-[10px] font-black uppercase text-gray-400 tracking-widest">Analytical Score (ISO 31000)</label>
                                    <div className="grid grid-cols-2 gap-4">
                                        <select className="w-full p-4 bg-gray-50 dark:bg-gray-900 rounded-2xl border-none">
                                            <option>Likelihood: 3</option>
                                        </select>
                                        <select className="w-full p-4 bg-gray-50 dark:bg-gray-900 rounded-2xl border-none">
                                            <option>Impact: 4</option>
                                        </select>
                                    </div>
                                    <div className="p-6 bg-teal-50 dark:bg-teal-900/20 rounded-3xl border border-teal-100 dark:border-teal-800 text-center">
                                        <p className="text-[10px] font-black text-teal-600 uppercase tracking-[0.3em] mb-2">Calculated Score</p>
                                        <p className="text-4xl font-black italic text-teal-700 dark:text-teal-300">12</p>
                                    </div>
                                </div>
                            </div>
                        </main>
                        <footer className="p-8 border-t border-gray-100 dark:border-gray-700 flex justify-end gap-3">
                             <button onClick={() => setIsModalOpen(false)} className="px-8 py-3 rounded-2xl font-black text-xs uppercase tracking-widest text-gray-500 hover:text-gray-900 transition-colors">Cancel</button>
                             <button className="px-8 py-3 bg-teal-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-teal-700 transition-all shadow-lg shadow-teal-500/20">Commit Changes</button>
                        </footer>
                     </div>
                </div>
            )}

            {isKhalidActive && (
                <KhalidAssistant 
                    onClose={() => { setIsKhalidActive(false); setIsModalOpen(false); setActiveField(null); }}
                    onUpdateField={(field, value) => setAiRiskDraft(prev => ({ ...prev, [field]: value }))}
                    onFocusField={(field) => setActiveField(field)}
                    onSaveRisk={() => handleSaveRisk({ ...aiRiskDraft, id: `ai-risk-${Date.now()}` } as Risk)}
                    onGenerateReport={handleGenerateOfficialReport}
                    currentRiskData={aiRiskDraft}
                />
            )}
        </div>
    );
};
